version: 2

builds:
  - id: "windows"
    main: ./cmd/billbank
    binary: >-
      billbank{{ .ShortCommit }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w
      - -X github.com/jaeiya/billbank/lib.appVersion={{ .Version }}
      - -X github.com/jaeiya/billbank/lib.commitSha={{ .ShortCommit }}
    goos:
      - windows
    goarch:
      - amd64
    goamd64:
      - v3
    no_unique_dist_dir: true

  - id: "unix"
    main: ./cmd/billbank
    binary: >-
      billbank{{ .ShortCommit }}_{{ .Os }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w
      - -X github.com/jaeiya/billbank/lib.appVersion={{ .Version }}
      - -X github.com/jaeiya/billbank/lib.commitSha={{ .ShortCommit }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    goamd64:
      - v3
    no_unique_dist_dir: true

  - id: "windows-upx"
    main: ./cmd/billbank
    skip: true # Set false if you want UPX for windows binaries
    binary: >-
      billbank{{ .ShortCommit }}_upx
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w
      - -X github.com/jaeiya/billbank/lib.appVersion={{ .Version }}
      - -X github.com/jaeiya/billbank/lib.commitSha={{ .ShortCommit }}
    goos:
      - windows
    goarch:
      - amd64
    goamd64:
      - v3
    no_unique_dist_dir: true
    hooks:
      post: # Hook to run after the build
        - upx --best --lzma -qq --force-overwrite {{ .Path }}

  - id: "unix-upx"
    main: ./cmd/billbank
    skip: true # Set false if you want UPX for unix (linux, darwin) binaries
    binary: >-
      billbank{{ .ShortCommit }}_{{ .Os }}_upx
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    gcflags:
      - "all=-B -l=120"
    ldflags:
      - -s -w
      - -X github.com/jaeiya/billbank/lib.appVersion={{ .Version }}
      - -X github.com/jaeiya/billbank/lib.commitSha={{ .ShortCommit }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
    goamd64:
      - v3
    no_unique_dist_dir: true
    hooks:
      post: # Hook to run after the build
        - upx --best --lzma -qq --force-overwrite --force-macos {{ .Path }}

snapshot:
  version_template: "build-{{ .ShortCommit }}"

checksum:
  disable: true

archives:
  - format: binary
